rabbitedit:
	@echo Please run \"make install\" or \"make uninstall\".
install:
	python setup.py install
	rm -rf build
uninstall:
	rm -rf /etc/rabbitedit /usr/bin/rabbitedit /usr/lib/python*/site-packages/rabbitedit-*.egg-info
.PHONY: rabbitedit install uninstall
