rabbitedit:
	@echo Please run \"make install\" or \"make uninstall\".
install:
	python setup.py install
	rm -rf build
uninstall:
	rm -rf /etc/rabbitedit /usr/bin/rabbitedit
.PHONY: rabbitedit install uninstall
